# Loads default set of integrations. Do not remove.
default_config:


homeassistant:
  allowlist_external_dirs:
  - "/config"
#
# uncomment here to activate new stuff
#
  #
  # WORKAROUND: put all custom automations here !!
  #
  packages: !include_dir_named packages/


# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes


# Text to speech
# tts:
#  - platform: pc


influxdb:
  api_version: 2
  ssl: false
  host: homeassistant
  port: 8096
  token: 1gqxzEV5NUIe5DWos7Yn1uvUoNUpqyx9cFWdIHkqfbrlNPXB825AZEOUGdJu8OoBZXrvIP4qRYGUgibfTYoB3A==
  organization: homeassistant
  bucket: data
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: units
  precision: s
  exclude:
    entities:
      - zone.home
    domains:
      - persistent_notification
      - person
  include:
    domains:
      - sensor
      - binary_sensor
      - sun
    entities:
      - weather.home


#
#recorder:
#  purge_keep_days: 60
#
recorder:
  auto_purge: true
  purge_keep_days: 58
  auto_repack: true
  exclude:
    domains:
      - automation
      - switch
      - light
      - update
      - person
      - zone
      - weather
      - schedule
      - device_tracker
      - media_player
      - sun
      - remote
      - select
      - number
    entities:
      - sensor.tasmota_energy_supply


# automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


#lovelace:
#  mode: yaml
